//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gcafePrnConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class setmeal_item
    {
        public setmeal_item()
        {
            this.setmeal_item_opt = new HashSet<setmeal_item_opt>();
        }
    
        public int id { get; set; }
        public int setmeal_menu_id { get; set; }
        public int setmeal_item_menu_id { get; set; }
    
        public virtual menu menu { get; set; }
        public virtual menu menu1 { get; set; }
        public virtual ICollection<setmeal_item_opt> setmeal_item_opt { get; set; }
    }
}
