//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace gcafeWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class branch
    {
        public branch()
        {
            this.member_refill = new HashSet<member_refill>();
            this.Menu = new HashSet<Menu>();
            this.order = new HashSet<order>();
            this.printer_group = new HashSet<printer_group>();
            this.staff = new HashSet<staff>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<member_refill> member_refill { get; set; }
        public virtual ICollection<Menu> Menu { get; set; }
        public virtual ICollection<order> order { get; set; }
        public virtual ICollection<printer_group> printer_group { get; set; }
        public virtual ICollection<staff> staff { get; set; }
    }
}
