//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace gcafeWeb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gcafeEntities : DbContext
    {
        public gcafeEntities()
            : base("name=gcafeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<branch> branch { get; set; }
        public DbSet<credit> credit { get; set; }
        public DbSet<member> member { get; set; }
        public DbSet<member_refill> member_refill { get; set; }
        public DbSet<Menu> Menu { get; set; }
        public DbSet<order> order { get; set; }
        public DbSet<order_detail> order_detail { get; set; }
        public DbSet<order_detail_print> order_detail_print { get; set; }
        public DbSet<printer> printer { get; set; }
        public DbSet<printer_group> printer_group { get; set; }
        public DbSet<role> role { get; set; }
        public DbSet<setmeal_item> setmeal_item { get; set; }
        public DbSet<setmeal_item_opt> setmeal_item_opt { get; set; }
        public DbSet<shift> shift { get; set; }
        public DbSet<staff> staff { get; set; }
    }
}
