//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gcafeWeb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gcafeEntities : DbContext
    {
        public gcafeEntities()
            : base("name=gcafeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<branch> branch { get; set; }
        public virtual DbSet<credit> credit { get; set; }
        public virtual DbSet<device> device { get; set; }
        public virtual DbSet<member> member { get; set; }
        public virtual DbSet<member_refill> member_refill { get; set; }
        public virtual DbSet<menu> menu { get; set; }
        public virtual DbSet<menu_catalog> menu_catalog { get; set; }
        public virtual DbSet<method> method { get; set; }
        public virtual DbSet<method_catalog> method_catalog { get; set; }
        public virtual DbSet<order> order { get; set; }
        public virtual DbSet<order_detail> order_detail { get; set; }
        public virtual DbSet<order_detail_method> order_detail_method { get; set; }
        public virtual DbSet<order_detail_setmeal> order_detail_setmeal { get; set; }
        public virtual DbSet<printer> printer { get; set; }
        public virtual DbSet<printer_group> printer_group { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<service> service { get; set; }
        public virtual DbSet<setmeal_item> setmeal_item { get; set; }
        public virtual DbSet<setmeal_item_opt> setmeal_item_opt { get; set; }
        public virtual DbSet<shift> shift { get; set; }
        public virtual DbSet<shift_detail> shift_detail { get; set; }
        public virtual DbSet<staff> staff { get; set; }
        public virtual DbSet<sys_info> sys_info { get; set; }
    }
}
