//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace gcafeWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class member
    {
        public member()
        {
            this.credit1 = new HashSet<credit>();
            this.member_refill = new HashSet<member_refill>();
            this.order = new HashSet<order>();
        }
    
        public int id { get; set; }
        public string idcard_number { get; set; }
        public string name { get; set; }
        public string phone_num { get; set; }
        public string email { get; set; }
        public int point { get; set; }
        public decimal credit { get; set; }
        public System.DateTime join_date { get; set; }
    
        public virtual ICollection<credit> credit1 { get; set; }
        public virtual ICollection<member_refill> member_refill { get; set; }
        public virtual ICollection<order> order { get; set; }
    }
}
