//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace gcafeWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class member_refill
    {
        public int id { get; set; }
        public int branch_id { get; set; }
        public int member_id { get; set; }
        public decimal refill_amount { get; set; }
        public int staff_id { get; set; }
        public System.DateTime refill_time { get; set; }
    
        public virtual branch branch { get; set; }
        public virtual member member { get; set; }
        public virtual staff staff { get; set; }
    }
}
