//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace gcafeWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public Menu()
        {
            this.order_detail = new HashSet<order_detail>();
            this.order_detail_print = new HashSet<order_detail_print>();
            this.order_detail_print1 = new HashSet<order_detail_print>();
            this.setmeal_item = new HashSet<setmeal_item>();
            this.setmeal_item_opt = new HashSet<setmeal_item_opt>();
            this.setmeal_item_opt1 = new HashSet<setmeal_item_opt>();
            this.setmeal_item1 = new HashSet<setmeal_item>();
        }
    
        public int id { get; set; }
        public int branch_id { get; set; }
        public string name { get; set; }
        public string number { get; set; }
        public string unit { get; set; }
        public decimal price { get; set; }
        public int printer_group_id { get; set; }
        public bool is_setmeal { get; set; }
        public bool is_locked { get; set; }
        public bool sold_out { get; set; }
    
        public virtual branch branch { get; set; }
        public virtual printer_group printer_group { get; set; }
        public virtual ICollection<order_detail> order_detail { get; set; }
        public virtual ICollection<order_detail_print> order_detail_print { get; set; }
        public virtual ICollection<order_detail_print> order_detail_print1 { get; set; }
        public virtual ICollection<setmeal_item> setmeal_item { get; set; }
        public virtual ICollection<setmeal_item_opt> setmeal_item_opt { get; set; }
        public virtual ICollection<setmeal_item_opt> setmeal_item_opt1 { get; set; }
        public virtual ICollection<setmeal_item> setmeal_item1 { get; set; }
    }
}
