//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace gcafeWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_detail
    {
        public order_detail()
        {
            this.order_detail_print = new HashSet<order_detail_print>();
        }
    
        public int id { get; set; }
        public int order_id { get; set; }
        public int menu_id { get; set; }
        public decimal quantity { get; set; }
        public decimal price { get; set; }
        public int order_staff_id { get; set; }
        public System.DateTime order_time { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual order order { get; set; }
        public virtual ICollection<order_detail_print> order_detail_print { get; set; }
        public virtual staff staff { get; set; }
    }
}
