//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace gcafeWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_detail_print
    {
        public int id { get; set; }
        public int order_detail_id { get; set; }
        public int menu_id { get; set; }
        public Nullable<int> setmeal_menu_id { get; set; }
        public string method { get; set; }
        public string serving { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual Menu Menu1 { get; set; }
        public virtual order_detail order_detail { get; set; }
    }
}
