//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gcafeWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class shift
    {
        public shift()
        {
            this.order = new HashSet<order>();
        }
    
        public int id { get; set; }
        public decimal sum { get; set; }
        public System.DateTime time { get; set; }
        public string staff_id { get; set; }
    
        public virtual ICollection<order> order { get; set; }
    }
}
