//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foxpro2Db.gcafeSvc {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.datacontract.org/2004/07/gcafeWeb", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Order : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TableNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TableNo {
            get {
                return this.TableNoField;
            }
            set {
                if ((object.ReferenceEquals(this.TableNoField, value) != true)) {
                    this.TableNoField = value;
                    this.RaisePropertyChanged("TableNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MenuItem", Namespace="http://schemas.datacontract.org/2004/07/gcafeWeb", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class MenuItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSetmealField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Foxpro2Db.gcafeSvc.SetmealItem[] SetmealItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnitField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSetmeal {
            get {
                return this.IsSetmealField;
            }
            set {
                if ((this.IsSetmealField.Equals(value) != true)) {
                    this.IsSetmealField = value;
                    this.RaisePropertyChanged("IsSetmeal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Foxpro2Db.gcafeSvc.SetmealItem[] SetmealItems {
            get {
                return this.SetmealItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.SetmealItemsField, value) != true)) {
                    this.SetmealItemsField = value;
                    this.RaisePropertyChanged("SetmealItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Unit {
            get {
                return this.UnitField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitField, value) != true)) {
                    this.UnitField = value;
                    this.RaisePropertyChanged("Unit");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SetmealItem", Namespace="http://schemas.datacontract.org/2004/07/gcafeWeb", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class SetmealItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Foxpro2Db.gcafeSvc.SetmealItem[] OptionItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnitField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Foxpro2Db.gcafeSvc.SetmealItem[] OptionItems {
            get {
                return this.OptionItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.OptionItemsField, value) != true)) {
                    this.OptionItemsField = value;
                    this.RaisePropertyChanged("OptionItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Unit {
            get {
                return this.UnitField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitField, value) != true)) {
                    this.UnitField = value;
                    this.RaisePropertyChanged("Unit");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MenuCatalog", Namespace="http://schemas.datacontract.org/2004/07/gcafeWeb", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class MenuCatalog : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ParentIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParentID {
            get {
                return this.ParentIDField;
            }
            set {
                if ((this.ParentIDField.Equals(value) != true)) {
                    this.ParentIDField = value;
                    this.RaisePropertyChanged("ParentID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="gcafeSvc.IgcafeSvc")]
    public interface IgcafeSvc {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IgcafeSvc/DoWork", ReplyAction="http://tempuri.org/IgcafeSvc/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IgcafeSvc/DoWork", ReplyAction="http://tempuri.org/IgcafeSvc/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IgcafeSvc/GetOrders", ReplyAction="http://tempuri.org/IgcafeSvc/GetOrdersResponse")]
        Foxpro2Db.gcafeSvc.Order[] GetOrders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IgcafeSvc/GetOrders", ReplyAction="http://tempuri.org/IgcafeSvc/GetOrdersResponse")]
        System.Threading.Tasks.Task<Foxpro2Db.gcafeSvc.Order[]> GetOrdersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IgcafeSvc/GetMenu", ReplyAction="http://tempuri.org/IgcafeSvc/GetMenuResponse")]
        Foxpro2Db.gcafeSvc.MenuItem[] GetMenu();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IgcafeSvc/GetMenu", ReplyAction="http://tempuri.org/IgcafeSvc/GetMenuResponse")]
        System.Threading.Tasks.Task<Foxpro2Db.gcafeSvc.MenuItem[]> GetMenuAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IgcafeSvc/GetMenuCatalogs", ReplyAction="http://tempuri.org/IgcafeSvc/GetMenuCatalogsResponse")]
        Foxpro2Db.gcafeSvc.MenuCatalog[] GetMenuCatalogs(string rootCata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IgcafeSvc/GetMenuCatalogs", ReplyAction="http://tempuri.org/IgcafeSvc/GetMenuCatalogsResponse")]
        System.Threading.Tasks.Task<Foxpro2Db.gcafeSvc.MenuCatalog[]> GetMenuCatalogsAsync(string rootCata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IgcafeSvc/GetMenuItemByCatalogId", ReplyAction="http://tempuri.org/IgcafeSvc/GetMenuItemByCatalogIdResponse")]
        Foxpro2Db.gcafeSvc.MenuItem[] GetMenuItemByCatalogId(int cataId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IgcafeSvc/GetMenuItemByCatalogId", ReplyAction="http://tempuri.org/IgcafeSvc/GetMenuItemByCatalogIdResponse")]
        System.Threading.Tasks.Task<Foxpro2Db.gcafeSvc.MenuItem[]> GetMenuItemByCatalogIdAsync(int cataId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IgcafeSvcChannel : Foxpro2Db.gcafeSvc.IgcafeSvc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IgcafeSvcClient : System.ServiceModel.ClientBase<Foxpro2Db.gcafeSvc.IgcafeSvc>, Foxpro2Db.gcafeSvc.IgcafeSvc {
        
        public IgcafeSvcClient() {
        }
        
        public IgcafeSvcClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IgcafeSvcClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IgcafeSvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IgcafeSvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public Foxpro2Db.gcafeSvc.Order[] GetOrders() {
            return base.Channel.GetOrders();
        }
        
        public System.Threading.Tasks.Task<Foxpro2Db.gcafeSvc.Order[]> GetOrdersAsync() {
            return base.Channel.GetOrdersAsync();
        }
        
        public Foxpro2Db.gcafeSvc.MenuItem[] GetMenu() {
            return base.Channel.GetMenu();
        }
        
        public System.Threading.Tasks.Task<Foxpro2Db.gcafeSvc.MenuItem[]> GetMenuAsync() {
            return base.Channel.GetMenuAsync();
        }
        
        public Foxpro2Db.gcafeSvc.MenuCatalog[] GetMenuCatalogs(string rootCata) {
            return base.Channel.GetMenuCatalogs(rootCata);
        }
        
        public System.Threading.Tasks.Task<Foxpro2Db.gcafeSvc.MenuCatalog[]> GetMenuCatalogsAsync(string rootCata) {
            return base.Channel.GetMenuCatalogsAsync(rootCata);
        }
        
        public Foxpro2Db.gcafeSvc.MenuItem[] GetMenuItemByCatalogId(int cataId) {
            return base.Channel.GetMenuItemByCatalogId(cataId);
        }
        
        public System.Threading.Tasks.Task<Foxpro2Db.gcafeSvc.MenuItem[]> GetMenuItemByCatalogIdAsync(int cataId) {
            return base.Channel.GetMenuItemByCatalogIdAsync(cataId);
        }
    }
}
