//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gcafeWeb.gcafePrnSvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="gcafePrnSvc.IgcafePrn")]
    public interface IgcafePrn {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IgcafePrn/PrintLiuTai", ReplyAction="http://tempuri.org/IgcafePrn/PrintLiuTaiResponse")]
        string PrintLiuTai(int orderId, int prnType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IgcafePrn/PrintLiuTai", ReplyAction="http://tempuri.org/IgcafePrn/PrintLiuTaiResponse")]
        System.Threading.Tasks.Task<string> PrintLiuTaiAsync(int orderId, int prnType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IgcafePrn/PrintHuaDan", ReplyAction="http://tempuri.org/IgcafePrn/PrintHuaDanResponse")]
        string PrintHuaDan(int orderId, int prnType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IgcafePrn/PrintHuaDan", ReplyAction="http://tempuri.org/IgcafePrn/PrintHuaDanResponse")]
        System.Threading.Tasks.Task<string> PrintHuaDanAsync(int orderId, int prnType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IgcafePrn/PrintChuPing", ReplyAction="http://tempuri.org/IgcafePrn/PrintChuPingResponse")]
        string PrintChuPing(int orderId, int prnType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IgcafePrn/PrintChuPing", ReplyAction="http://tempuri.org/IgcafePrn/PrintChuPingResponse")]
        System.Threading.Tasks.Task<string> PrintChuPingAsync(int orderId, int prnType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IgcafePrn/PrintChuPingCui", ReplyAction="http://tempuri.org/IgcafePrn/PrintChuPingCuiResponse")]
        string PrintChuPingCui(int orderId, int orderDetailId, int setmailId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IgcafePrn/PrintChuPingCui", ReplyAction="http://tempuri.org/IgcafePrn/PrintChuPingCuiResponse")]
        System.Threading.Tasks.Task<string> PrintChuPingCuiAsync(int orderId, int orderDetailId, int setmailId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IgcafePrnChannel : gcafeWeb.gcafePrnSvc.IgcafePrn, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IgcafePrnClient : System.ServiceModel.ClientBase<gcafeWeb.gcafePrnSvc.IgcafePrn>, gcafeWeb.gcafePrnSvc.IgcafePrn {
        
        public IgcafePrnClient() {
        }
        
        public IgcafePrnClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IgcafePrnClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IgcafePrnClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IgcafePrnClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string PrintLiuTai(int orderId, int prnType) {
            return base.Channel.PrintLiuTai(orderId, prnType);
        }
        
        public System.Threading.Tasks.Task<string> PrintLiuTaiAsync(int orderId, int prnType) {
            return base.Channel.PrintLiuTaiAsync(orderId, prnType);
        }
        
        public string PrintHuaDan(int orderId, int prnType) {
            return base.Channel.PrintHuaDan(orderId, prnType);
        }
        
        public System.Threading.Tasks.Task<string> PrintHuaDanAsync(int orderId, int prnType) {
            return base.Channel.PrintHuaDanAsync(orderId, prnType);
        }
        
        public string PrintChuPing(int orderId, int prnType) {
            return base.Channel.PrintChuPing(orderId, prnType);
        }
        
        public System.Threading.Tasks.Task<string> PrintChuPingAsync(int orderId, int prnType) {
            return base.Channel.PrintChuPingAsync(orderId, prnType);
        }
        
        public string PrintChuPingCui(int orderId, int orderDetailId, int setmailId) {
            return base.Channel.PrintChuPingCui(orderId, orderDetailId, setmailId);
        }
        
        public System.Threading.Tasks.Task<string> PrintChuPingCuiAsync(int orderId, int orderDetailId, int setmailId) {
            return base.Channel.PrintChuPingCuiAsync(orderId, orderDetailId, setmailId);
        }
    }
}
