//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gcafeFoxproSvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class credit
    {
        public int id { get; set; }
        public int order_id { get; set; }
        public Nullable<int> member_id { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public Nullable<System.DateTime> repay_time { get; set; }
    
        public virtual member member { get; set; }
        public virtual order order { get; set; }
    }
}
