//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace gcafeApp.gcafeSvc {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MenuCatalog", Namespace="http://schemas.datacontract.org/2004/07/gcafeWeb", IsReference=true)]
    public partial class MenuCatalog : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int IDField;
        
        private string NameField;
        
        private int ParentIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParentID {
            get {
                return this.ParentIDField;
            }
            set {
                if ((this.ParentIDField.Equals(value) != true)) {
                    this.ParentIDField = value;
                    this.RaisePropertyChanged("ParentID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MenuItem", Namespace="http://schemas.datacontract.org/2004/07/gcafeWeb", IsReference=true)]
    public partial class MenuItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int IDField;
        
        private bool IsSetmealField;
        
        private string NameField;
        
        private decimal PriceField;
        
        private System.Collections.ObjectModel.ObservableCollection<gcafeApp.gcafeSvc.SetmealItem> SetmealItemsField;
        
        private string UnitField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSetmeal {
            get {
                return this.IsSetmealField;
            }
            set {
                if ((this.IsSetmealField.Equals(value) != true)) {
                    this.IsSetmealField = value;
                    this.RaisePropertyChanged("IsSetmeal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<gcafeApp.gcafeSvc.SetmealItem> SetmealItems {
            get {
                return this.SetmealItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.SetmealItemsField, value) != true)) {
                    this.SetmealItemsField = value;
                    this.RaisePropertyChanged("SetmealItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Unit {
            get {
                return this.UnitField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitField, value) != true)) {
                    this.UnitField = value;
                    this.RaisePropertyChanged("Unit");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SetmealItem", Namespace="http://schemas.datacontract.org/2004/07/gcafeWeb", IsReference=true)]
    public partial class SetmealItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string NameField;
        
        private System.Collections.ObjectModel.ObservableCollection<gcafeApp.gcafeSvc.SetmealItem> OptionItemsField;
        
        private string UnitField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<gcafeApp.gcafeSvc.SetmealItem> OptionItems {
            get {
                return this.OptionItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.OptionItemsField, value) != true)) {
                    this.OptionItemsField = value;
                    this.RaisePropertyChanged("OptionItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Unit {
            get {
                return this.UnitField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitField, value) != true)) {
                    this.UnitField = value;
                    this.RaisePropertyChanged("Unit");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Staff", Namespace="http://schemas.datacontract.org/2004/07/gcafeWeb", IsReference=true)]
    public partial class Staff : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string BranchField;
        
        private int BranchIDField;
        
        private int IDField;
        
        private string NameField;
        
        private string NumberField;
        
        private string PasswordField;
        
        private int RoleIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Branch {
            get {
                return this.BranchField;
            }
            set {
                if ((object.ReferenceEquals(this.BranchField, value) != true)) {
                    this.BranchField = value;
                    this.RaisePropertyChanged("Branch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BranchID {
            get {
                return this.BranchIDField;
            }
            set {
                if ((this.BranchIDField.Equals(value) != true)) {
                    this.BranchIDField = value;
                    this.RaisePropertyChanged("BranchID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Number {
            get {
                return this.NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberField, value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RoleID {
            get {
                return this.RoleIDField;
            }
            set {
                if ((this.RoleIDField.Equals(value) != true)) {
                    this.RoleIDField = value;
                    this.RaisePropertyChanged("RoleID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="gcafeSvc.IgcafeSvc")]
    public interface IgcafeSvc {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IgcafeSvc/GetMenuCatalogs", ReplyAction="http://tempuri.org/IgcafeSvc/GetMenuCatalogsResponse")]
        System.IAsyncResult BeginGetMenuCatalogs(gcafeApp.gcafeSvc.GetMenuCatalogsRequest request, System.AsyncCallback callback, object asyncState);
        
        gcafeApp.gcafeSvc.GetMenuCatalogsResponse EndGetMenuCatalogs(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IgcafeSvc/GetMenuItemsByCatalogId", ReplyAction="http://tempuri.org/IgcafeSvc/GetMenuItemsByCatalogIdResponse")]
        System.IAsyncResult BeginGetMenuItemsByCatalogId(gcafeApp.gcafeSvc.GetMenuItemsByCatalogIdRequest request, System.AsyncCallback callback, object asyncState);
        
        gcafeApp.gcafeSvc.GetMenuItemsByCatalogIdResponse EndGetMenuItemsByCatalogId(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IgcafeSvc/GetMenuItemByNumber", ReplyAction="http://tempuri.org/IgcafeSvc/GetMenuItemByNumberResponse")]
        System.IAsyncResult BeginGetMenuItemByNumber(gcafeApp.gcafeSvc.GetMenuItemByNumberRequest request, System.AsyncCallback callback, object asyncState);
        
        gcafeApp.gcafeSvc.GetMenuItemByNumberResponse EndGetMenuItemByNumber(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IgcafeSvc/GetStaffByNum", ReplyAction="http://tempuri.org/IgcafeSvc/GetStaffByNumResponse")]
        System.IAsyncResult BeginGetStaffByNum(gcafeApp.gcafeSvc.GetStaffByNumRequest request, System.AsyncCallback callback, object asyncState);
        
        gcafeApp.gcafeSvc.GetStaffByNumResponse EndGetStaffByNum(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMenuCatalogs", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetMenuCatalogsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string rootCata;
        
        public GetMenuCatalogsRequest() {
        }
        
        public GetMenuCatalogsRequest(string rootCata) {
            this.rootCata = rootCata;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMenuCatalogsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetMenuCatalogsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.ObjectModel.ObservableCollection<gcafeApp.gcafeSvc.MenuCatalog> GetMenuCatalogsResult;
        
        public GetMenuCatalogsResponse() {
        }
        
        public GetMenuCatalogsResponse(System.Collections.ObjectModel.ObservableCollection<gcafeApp.gcafeSvc.MenuCatalog> GetMenuCatalogsResult) {
            this.GetMenuCatalogsResult = GetMenuCatalogsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMenuItemsByCatalogId", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetMenuItemsByCatalogIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int branchId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int cataId;
        
        public GetMenuItemsByCatalogIdRequest() {
        }
        
        public GetMenuItemsByCatalogIdRequest(int branchId, int cataId) {
            this.branchId = branchId;
            this.cataId = cataId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMenuItemsByCatalogIdResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetMenuItemsByCatalogIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.ObjectModel.ObservableCollection<gcafeApp.gcafeSvc.MenuItem> GetMenuItemsByCatalogIdResult;
        
        public GetMenuItemsByCatalogIdResponse() {
        }
        
        public GetMenuItemsByCatalogIdResponse(System.Collections.ObjectModel.ObservableCollection<gcafeApp.gcafeSvc.MenuItem> GetMenuItemsByCatalogIdResult) {
            this.GetMenuItemsByCatalogIdResult = GetMenuItemsByCatalogIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMenuItemByNumber", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetMenuItemByNumberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string number;
        
        public GetMenuItemByNumberRequest() {
        }
        
        public GetMenuItemByNumberRequest(string number) {
            this.number = number;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMenuItemByNumberResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetMenuItemByNumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public gcafeApp.gcafeSvc.MenuItem GetMenuItemByNumberResult;
        
        public GetMenuItemByNumberResponse() {
        }
        
        public GetMenuItemByNumberResponse(gcafeApp.gcafeSvc.MenuItem GetMenuItemByNumberResult) {
            this.GetMenuItemByNumberResult = GetMenuItemByNumberResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStaffByNum", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetStaffByNumRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Num;
        
        public GetStaffByNumRequest() {
        }
        
        public GetStaffByNumRequest(string Num) {
            this.Num = Num;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStaffByNumResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetStaffByNumResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public gcafeApp.gcafeSvc.Staff GetStaffByNumResult;
        
        public GetStaffByNumResponse() {
        }
        
        public GetStaffByNumResponse(gcafeApp.gcafeSvc.Staff GetStaffByNumResult) {
            this.GetStaffByNumResult = GetStaffByNumResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IgcafeSvcChannel : gcafeApp.gcafeSvc.IgcafeSvc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetMenuCatalogsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetMenuCatalogsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public gcafeApp.gcafeSvc.GetMenuCatalogsResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((gcafeApp.gcafeSvc.GetMenuCatalogsResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetMenuItemsByCatalogIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetMenuItemsByCatalogIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public gcafeApp.gcafeSvc.GetMenuItemsByCatalogIdResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((gcafeApp.gcafeSvc.GetMenuItemsByCatalogIdResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetMenuItemByNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetMenuItemByNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public gcafeApp.gcafeSvc.GetMenuItemByNumberResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((gcafeApp.gcafeSvc.GetMenuItemByNumberResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetStaffByNumCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetStaffByNumCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public gcafeApp.gcafeSvc.GetStaffByNumResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((gcafeApp.gcafeSvc.GetStaffByNumResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IgcafeSvcClient : System.ServiceModel.ClientBase<gcafeApp.gcafeSvc.IgcafeSvc>, gcafeApp.gcafeSvc.IgcafeSvc {
        
        private BeginOperationDelegate onBeginGetMenuCatalogsDelegate;
        
        private EndOperationDelegate onEndGetMenuCatalogsDelegate;
        
        private System.Threading.SendOrPostCallback onGetMenuCatalogsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetMenuItemsByCatalogIdDelegate;
        
        private EndOperationDelegate onEndGetMenuItemsByCatalogIdDelegate;
        
        private System.Threading.SendOrPostCallback onGetMenuItemsByCatalogIdCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetMenuItemByNumberDelegate;
        
        private EndOperationDelegate onEndGetMenuItemByNumberDelegate;
        
        private System.Threading.SendOrPostCallback onGetMenuItemByNumberCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetStaffByNumDelegate;
        
        private EndOperationDelegate onEndGetStaffByNumDelegate;
        
        private System.Threading.SendOrPostCallback onGetStaffByNumCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public IgcafeSvcClient() {
        }
        
        public IgcafeSvcClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IgcafeSvcClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IgcafeSvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IgcafeSvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetMenuCatalogsCompletedEventArgs> GetMenuCatalogsCompleted;
        
        public event System.EventHandler<GetMenuItemsByCatalogIdCompletedEventArgs> GetMenuItemsByCatalogIdCompleted;
        
        public event System.EventHandler<GetMenuItemByNumberCompletedEventArgs> GetMenuItemByNumberCompleted;
        
        public event System.EventHandler<GetStaffByNumCompletedEventArgs> GetStaffByNumCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult gcafeApp.gcafeSvc.IgcafeSvc.BeginGetMenuCatalogs(gcafeApp.gcafeSvc.GetMenuCatalogsRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetMenuCatalogs(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        gcafeApp.gcafeSvc.GetMenuCatalogsResponse gcafeApp.gcafeSvc.IgcafeSvc.EndGetMenuCatalogs(System.IAsyncResult result) {
            return base.Channel.EndGetMenuCatalogs(result);
        }
        
        private System.IAsyncResult OnBeginGetMenuCatalogs(object[] inValues, System.AsyncCallback callback, object asyncState) {
            gcafeApp.gcafeSvc.GetMenuCatalogsRequest request = ((gcafeApp.gcafeSvc.GetMenuCatalogsRequest)(inValues[0]));
            return ((gcafeApp.gcafeSvc.IgcafeSvc)(this)).BeginGetMenuCatalogs(request, callback, asyncState);
        }
        
        private object[] OnEndGetMenuCatalogs(System.IAsyncResult result) {
            gcafeApp.gcafeSvc.GetMenuCatalogsResponse retVal = ((gcafeApp.gcafeSvc.IgcafeSvc)(this)).EndGetMenuCatalogs(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetMenuCatalogsCompleted(object state) {
            if ((this.GetMenuCatalogsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetMenuCatalogsCompleted(this, new GetMenuCatalogsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetMenuCatalogsAsync(gcafeApp.gcafeSvc.GetMenuCatalogsRequest request) {
            this.GetMenuCatalogsAsync(request, null);
        }
        
        public void GetMenuCatalogsAsync(gcafeApp.gcafeSvc.GetMenuCatalogsRequest request, object userState) {
            if ((this.onBeginGetMenuCatalogsDelegate == null)) {
                this.onBeginGetMenuCatalogsDelegate = new BeginOperationDelegate(this.OnBeginGetMenuCatalogs);
            }
            if ((this.onEndGetMenuCatalogsDelegate == null)) {
                this.onEndGetMenuCatalogsDelegate = new EndOperationDelegate(this.OnEndGetMenuCatalogs);
            }
            if ((this.onGetMenuCatalogsCompletedDelegate == null)) {
                this.onGetMenuCatalogsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetMenuCatalogsCompleted);
            }
            base.InvokeAsync(this.onBeginGetMenuCatalogsDelegate, new object[] {
                        request}, this.onEndGetMenuCatalogsDelegate, this.onGetMenuCatalogsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult gcafeApp.gcafeSvc.IgcafeSvc.BeginGetMenuItemsByCatalogId(gcafeApp.gcafeSvc.GetMenuItemsByCatalogIdRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetMenuItemsByCatalogId(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        gcafeApp.gcafeSvc.GetMenuItemsByCatalogIdResponse gcafeApp.gcafeSvc.IgcafeSvc.EndGetMenuItemsByCatalogId(System.IAsyncResult result) {
            return base.Channel.EndGetMenuItemsByCatalogId(result);
        }
        
        private System.IAsyncResult OnBeginGetMenuItemsByCatalogId(object[] inValues, System.AsyncCallback callback, object asyncState) {
            gcafeApp.gcafeSvc.GetMenuItemsByCatalogIdRequest request = ((gcafeApp.gcafeSvc.GetMenuItemsByCatalogIdRequest)(inValues[0]));
            return ((gcafeApp.gcafeSvc.IgcafeSvc)(this)).BeginGetMenuItemsByCatalogId(request, callback, asyncState);
        }
        
        private object[] OnEndGetMenuItemsByCatalogId(System.IAsyncResult result) {
            gcafeApp.gcafeSvc.GetMenuItemsByCatalogIdResponse retVal = ((gcafeApp.gcafeSvc.IgcafeSvc)(this)).EndGetMenuItemsByCatalogId(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetMenuItemsByCatalogIdCompleted(object state) {
            if ((this.GetMenuItemsByCatalogIdCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetMenuItemsByCatalogIdCompleted(this, new GetMenuItemsByCatalogIdCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetMenuItemsByCatalogIdAsync(gcafeApp.gcafeSvc.GetMenuItemsByCatalogIdRequest request) {
            this.GetMenuItemsByCatalogIdAsync(request, null);
        }
        
        public void GetMenuItemsByCatalogIdAsync(gcafeApp.gcafeSvc.GetMenuItemsByCatalogIdRequest request, object userState) {
            if ((this.onBeginGetMenuItemsByCatalogIdDelegate == null)) {
                this.onBeginGetMenuItemsByCatalogIdDelegate = new BeginOperationDelegate(this.OnBeginGetMenuItemsByCatalogId);
            }
            if ((this.onEndGetMenuItemsByCatalogIdDelegate == null)) {
                this.onEndGetMenuItemsByCatalogIdDelegate = new EndOperationDelegate(this.OnEndGetMenuItemsByCatalogId);
            }
            if ((this.onGetMenuItemsByCatalogIdCompletedDelegate == null)) {
                this.onGetMenuItemsByCatalogIdCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetMenuItemsByCatalogIdCompleted);
            }
            base.InvokeAsync(this.onBeginGetMenuItemsByCatalogIdDelegate, new object[] {
                        request}, this.onEndGetMenuItemsByCatalogIdDelegate, this.onGetMenuItemsByCatalogIdCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult gcafeApp.gcafeSvc.IgcafeSvc.BeginGetMenuItemByNumber(gcafeApp.gcafeSvc.GetMenuItemByNumberRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetMenuItemByNumber(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        gcafeApp.gcafeSvc.GetMenuItemByNumberResponse gcafeApp.gcafeSvc.IgcafeSvc.EndGetMenuItemByNumber(System.IAsyncResult result) {
            return base.Channel.EndGetMenuItemByNumber(result);
        }
        
        private System.IAsyncResult OnBeginGetMenuItemByNumber(object[] inValues, System.AsyncCallback callback, object asyncState) {
            gcafeApp.gcafeSvc.GetMenuItemByNumberRequest request = ((gcafeApp.gcafeSvc.GetMenuItemByNumberRequest)(inValues[0]));
            return ((gcafeApp.gcafeSvc.IgcafeSvc)(this)).BeginGetMenuItemByNumber(request, callback, asyncState);
        }
        
        private object[] OnEndGetMenuItemByNumber(System.IAsyncResult result) {
            gcafeApp.gcafeSvc.GetMenuItemByNumberResponse retVal = ((gcafeApp.gcafeSvc.IgcafeSvc)(this)).EndGetMenuItemByNumber(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetMenuItemByNumberCompleted(object state) {
            if ((this.GetMenuItemByNumberCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetMenuItemByNumberCompleted(this, new GetMenuItemByNumberCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetMenuItemByNumberAsync(gcafeApp.gcafeSvc.GetMenuItemByNumberRequest request) {
            this.GetMenuItemByNumberAsync(request, null);
        }
        
        public void GetMenuItemByNumberAsync(gcafeApp.gcafeSvc.GetMenuItemByNumberRequest request, object userState) {
            if ((this.onBeginGetMenuItemByNumberDelegate == null)) {
                this.onBeginGetMenuItemByNumberDelegate = new BeginOperationDelegate(this.OnBeginGetMenuItemByNumber);
            }
            if ((this.onEndGetMenuItemByNumberDelegate == null)) {
                this.onEndGetMenuItemByNumberDelegate = new EndOperationDelegate(this.OnEndGetMenuItemByNumber);
            }
            if ((this.onGetMenuItemByNumberCompletedDelegate == null)) {
                this.onGetMenuItemByNumberCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetMenuItemByNumberCompleted);
            }
            base.InvokeAsync(this.onBeginGetMenuItemByNumberDelegate, new object[] {
                        request}, this.onEndGetMenuItemByNumberDelegate, this.onGetMenuItemByNumberCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult gcafeApp.gcafeSvc.IgcafeSvc.BeginGetStaffByNum(gcafeApp.gcafeSvc.GetStaffByNumRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetStaffByNum(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        gcafeApp.gcafeSvc.GetStaffByNumResponse gcafeApp.gcafeSvc.IgcafeSvc.EndGetStaffByNum(System.IAsyncResult result) {
            return base.Channel.EndGetStaffByNum(result);
        }
        
        private System.IAsyncResult OnBeginGetStaffByNum(object[] inValues, System.AsyncCallback callback, object asyncState) {
            gcafeApp.gcafeSvc.GetStaffByNumRequest request = ((gcafeApp.gcafeSvc.GetStaffByNumRequest)(inValues[0]));
            return ((gcafeApp.gcafeSvc.IgcafeSvc)(this)).BeginGetStaffByNum(request, callback, asyncState);
        }
        
        private object[] OnEndGetStaffByNum(System.IAsyncResult result) {
            gcafeApp.gcafeSvc.GetStaffByNumResponse retVal = ((gcafeApp.gcafeSvc.IgcafeSvc)(this)).EndGetStaffByNum(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetStaffByNumCompleted(object state) {
            if ((this.GetStaffByNumCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetStaffByNumCompleted(this, new GetStaffByNumCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetStaffByNumAsync(gcafeApp.gcafeSvc.GetStaffByNumRequest request) {
            this.GetStaffByNumAsync(request, null);
        }
        
        public void GetStaffByNumAsync(gcafeApp.gcafeSvc.GetStaffByNumRequest request, object userState) {
            if ((this.onBeginGetStaffByNumDelegate == null)) {
                this.onBeginGetStaffByNumDelegate = new BeginOperationDelegate(this.OnBeginGetStaffByNum);
            }
            if ((this.onEndGetStaffByNumDelegate == null)) {
                this.onEndGetStaffByNumDelegate = new EndOperationDelegate(this.OnEndGetStaffByNum);
            }
            if ((this.onGetStaffByNumCompletedDelegate == null)) {
                this.onGetStaffByNumCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetStaffByNumCompleted);
            }
            base.InvokeAsync(this.onBeginGetStaffByNumDelegate, new object[] {
                        request}, this.onEndGetStaffByNumDelegate, this.onGetStaffByNumCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override gcafeApp.gcafeSvc.IgcafeSvc CreateChannel() {
            return new IgcafeSvcClientChannel(this);
        }
        
        private class IgcafeSvcClientChannel : ChannelBase<gcafeApp.gcafeSvc.IgcafeSvc>, gcafeApp.gcafeSvc.IgcafeSvc {
            
            public IgcafeSvcClientChannel(System.ServiceModel.ClientBase<gcafeApp.gcafeSvc.IgcafeSvc> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetMenuCatalogs(gcafeApp.gcafeSvc.GetMenuCatalogsRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetMenuCatalogs", _args, callback, asyncState);
                return _result;
            }
            
            public gcafeApp.gcafeSvc.GetMenuCatalogsResponse EndGetMenuCatalogs(System.IAsyncResult result) {
                object[] _args = new object[0];
                gcafeApp.gcafeSvc.GetMenuCatalogsResponse _result = ((gcafeApp.gcafeSvc.GetMenuCatalogsResponse)(base.EndInvoke("GetMenuCatalogs", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetMenuItemsByCatalogId(gcafeApp.gcafeSvc.GetMenuItemsByCatalogIdRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetMenuItemsByCatalogId", _args, callback, asyncState);
                return _result;
            }
            
            public gcafeApp.gcafeSvc.GetMenuItemsByCatalogIdResponse EndGetMenuItemsByCatalogId(System.IAsyncResult result) {
                object[] _args = new object[0];
                gcafeApp.gcafeSvc.GetMenuItemsByCatalogIdResponse _result = ((gcafeApp.gcafeSvc.GetMenuItemsByCatalogIdResponse)(base.EndInvoke("GetMenuItemsByCatalogId", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetMenuItemByNumber(gcafeApp.gcafeSvc.GetMenuItemByNumberRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetMenuItemByNumber", _args, callback, asyncState);
                return _result;
            }
            
            public gcafeApp.gcafeSvc.GetMenuItemByNumberResponse EndGetMenuItemByNumber(System.IAsyncResult result) {
                object[] _args = new object[0];
                gcafeApp.gcafeSvc.GetMenuItemByNumberResponse _result = ((gcafeApp.gcafeSvc.GetMenuItemByNumberResponse)(base.EndInvoke("GetMenuItemByNumber", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetStaffByNum(gcafeApp.gcafeSvc.GetStaffByNumRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetStaffByNum", _args, callback, asyncState);
                return _result;
            }
            
            public gcafeApp.gcafeSvc.GetStaffByNumResponse EndGetStaffByNum(System.IAsyncResult result) {
                object[] _args = new object[0];
                gcafeApp.gcafeSvc.GetStaffByNumResponse _result = ((gcafeApp.gcafeSvc.GetStaffByNumResponse)(base.EndInvoke("GetStaffByNum", _args, result)));
                return _result;
            }
        }
    }
}
