//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace gcafeApp.gcafeSvc {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.datacontract.org/2004/07/gcafeWeb", IsReference=true)]
    public partial class Order : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string TableNoField;
        
        private int idField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TableNo {
            get {
                return this.TableNoField;
            }
            set {
                if ((object.ReferenceEquals(this.TableNoField, value) != true)) {
                    this.TableNoField = value;
                    this.RaisePropertyChanged("TableNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MenuItem", Namespace="http://schemas.datacontract.org/2004/07/gcafeWeb", IsReference=true)]
    public partial class MenuItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool IsSetmealField;
        
        private string NameField;
        
        private decimal PriceField;
        
        private System.Collections.ObjectModel.ObservableCollection<gcafeApp.gcafeSvc.SetmealItem> SetmealItemsField;
        
        private string UnitField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSetmeal {
            get {
                return this.IsSetmealField;
            }
            set {
                if ((this.IsSetmealField.Equals(value) != true)) {
                    this.IsSetmealField = value;
                    this.RaisePropertyChanged("IsSetmeal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<gcafeApp.gcafeSvc.SetmealItem> SetmealItems {
            get {
                return this.SetmealItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.SetmealItemsField, value) != true)) {
                    this.SetmealItemsField = value;
                    this.RaisePropertyChanged("SetmealItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Unit {
            get {
                return this.UnitField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitField, value) != true)) {
                    this.UnitField = value;
                    this.RaisePropertyChanged("Unit");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SetmealItem", Namespace="http://schemas.datacontract.org/2004/07/gcafeWeb", IsReference=true)]
    public partial class SetmealItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string NameField;
        
        private System.Collections.ObjectModel.ObservableCollection<gcafeApp.gcafeSvc.SetmealItem> OptionItemsField;
        
        private string UnitField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<gcafeApp.gcafeSvc.SetmealItem> OptionItems {
            get {
                return this.OptionItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.OptionItemsField, value) != true)) {
                    this.OptionItemsField = value;
                    this.RaisePropertyChanged("OptionItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Unit {
            get {
                return this.UnitField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitField, value) != true)) {
                    this.UnitField = value;
                    this.RaisePropertyChanged("Unit");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MenuCatalog", Namespace="http://schemas.datacontract.org/2004/07/gcafeWeb", IsReference=true)]
    public partial class MenuCatalog : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int IDField;
        
        private string NameField;
        
        private int ParentIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParentID {
            get {
                return this.ParentIDField;
            }
            set {
                if ((this.ParentIDField.Equals(value) != true)) {
                    this.ParentIDField = value;
                    this.RaisePropertyChanged("ParentID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="gcafeSvc.IgcafeSvc")]
    public interface IgcafeSvc {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IgcafeSvc/DoWork", ReplyAction="http://tempuri.org/IgcafeSvc/DoWorkResponse")]
        System.IAsyncResult BeginDoWork(System.AsyncCallback callback, object asyncState);
        
        void EndDoWork(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IgcafeSvc/GetOrders", ReplyAction="http://tempuri.org/IgcafeSvc/GetOrdersResponse")]
        System.IAsyncResult BeginGetOrders(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<gcafeApp.gcafeSvc.Order> EndGetOrders(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IgcafeSvc/GetMenu", ReplyAction="http://tempuri.org/IgcafeSvc/GetMenuResponse")]
        System.IAsyncResult BeginGetMenu(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<gcafeApp.gcafeSvc.MenuItem> EndGetMenu(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IgcafeSvc/GetMenuCatalogs", ReplyAction="http://tempuri.org/IgcafeSvc/GetMenuCatalogsResponse")]
        System.IAsyncResult BeginGetMenuCatalogs(string rootCata, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<gcafeApp.gcafeSvc.MenuCatalog> EndGetMenuCatalogs(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IgcafeSvc/GetMenuItemByCatalogId", ReplyAction="http://tempuri.org/IgcafeSvc/GetMenuItemByCatalogIdResponse")]
        System.IAsyncResult BeginGetMenuItemByCatalogId(int cataId, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<gcafeApp.gcafeSvc.MenuItem> EndGetMenuItemByCatalogId(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IgcafeSvcChannel : gcafeApp.gcafeSvc.IgcafeSvc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetOrdersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetOrdersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<gcafeApp.gcafeSvc.Order> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<gcafeApp.gcafeSvc.Order>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetMenuCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetMenuCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<gcafeApp.gcafeSvc.MenuItem> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<gcafeApp.gcafeSvc.MenuItem>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetMenuCatalogsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetMenuCatalogsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<gcafeApp.gcafeSvc.MenuCatalog> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<gcafeApp.gcafeSvc.MenuCatalog>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetMenuItemByCatalogIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetMenuItemByCatalogIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<gcafeApp.gcafeSvc.MenuItem> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<gcafeApp.gcafeSvc.MenuItem>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IgcafeSvcClient : System.ServiceModel.ClientBase<gcafeApp.gcafeSvc.IgcafeSvc>, gcafeApp.gcafeSvc.IgcafeSvc {
        
        private BeginOperationDelegate onBeginDoWorkDelegate;
        
        private EndOperationDelegate onEndDoWorkDelegate;
        
        private System.Threading.SendOrPostCallback onDoWorkCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetOrdersDelegate;
        
        private EndOperationDelegate onEndGetOrdersDelegate;
        
        private System.Threading.SendOrPostCallback onGetOrdersCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetMenuDelegate;
        
        private EndOperationDelegate onEndGetMenuDelegate;
        
        private System.Threading.SendOrPostCallback onGetMenuCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetMenuCatalogsDelegate;
        
        private EndOperationDelegate onEndGetMenuCatalogsDelegate;
        
        private System.Threading.SendOrPostCallback onGetMenuCatalogsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetMenuItemByCatalogIdDelegate;
        
        private EndOperationDelegate onEndGetMenuItemByCatalogIdDelegate;
        
        private System.Threading.SendOrPostCallback onGetMenuItemByCatalogIdCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public IgcafeSvcClient() {
        }
        
        public IgcafeSvcClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IgcafeSvcClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IgcafeSvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IgcafeSvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> DoWorkCompleted;
        
        public event System.EventHandler<GetOrdersCompletedEventArgs> GetOrdersCompleted;
        
        public event System.EventHandler<GetMenuCompletedEventArgs> GetMenuCompleted;
        
        public event System.EventHandler<GetMenuCatalogsCompletedEventArgs> GetMenuCatalogsCompleted;
        
        public event System.EventHandler<GetMenuItemByCatalogIdCompletedEventArgs> GetMenuItemByCatalogIdCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult gcafeApp.gcafeSvc.IgcafeSvc.BeginDoWork(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDoWork(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void gcafeApp.gcafeSvc.IgcafeSvc.EndDoWork(System.IAsyncResult result) {
            base.Channel.EndDoWork(result);
        }
        
        private System.IAsyncResult OnBeginDoWork(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((gcafeApp.gcafeSvc.IgcafeSvc)(this)).BeginDoWork(callback, asyncState);
        }
        
        private object[] OnEndDoWork(System.IAsyncResult result) {
            ((gcafeApp.gcafeSvc.IgcafeSvc)(this)).EndDoWork(result);
            return null;
        }
        
        private void OnDoWorkCompleted(object state) {
            if ((this.DoWorkCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DoWorkCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DoWorkAsync() {
            this.DoWorkAsync(null);
        }
        
        public void DoWorkAsync(object userState) {
            if ((this.onBeginDoWorkDelegate == null)) {
                this.onBeginDoWorkDelegate = new BeginOperationDelegate(this.OnBeginDoWork);
            }
            if ((this.onEndDoWorkDelegate == null)) {
                this.onEndDoWorkDelegate = new EndOperationDelegate(this.OnEndDoWork);
            }
            if ((this.onDoWorkCompletedDelegate == null)) {
                this.onDoWorkCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDoWorkCompleted);
            }
            base.InvokeAsync(this.onBeginDoWorkDelegate, null, this.onEndDoWorkDelegate, this.onDoWorkCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult gcafeApp.gcafeSvc.IgcafeSvc.BeginGetOrders(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetOrders(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<gcafeApp.gcafeSvc.Order> gcafeApp.gcafeSvc.IgcafeSvc.EndGetOrders(System.IAsyncResult result) {
            return base.Channel.EndGetOrders(result);
        }
        
        private System.IAsyncResult OnBeginGetOrders(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((gcafeApp.gcafeSvc.IgcafeSvc)(this)).BeginGetOrders(callback, asyncState);
        }
        
        private object[] OnEndGetOrders(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<gcafeApp.gcafeSvc.Order> retVal = ((gcafeApp.gcafeSvc.IgcafeSvc)(this)).EndGetOrders(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetOrdersCompleted(object state) {
            if ((this.GetOrdersCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetOrdersCompleted(this, new GetOrdersCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetOrdersAsync() {
            this.GetOrdersAsync(null);
        }
        
        public void GetOrdersAsync(object userState) {
            if ((this.onBeginGetOrdersDelegate == null)) {
                this.onBeginGetOrdersDelegate = new BeginOperationDelegate(this.OnBeginGetOrders);
            }
            if ((this.onEndGetOrdersDelegate == null)) {
                this.onEndGetOrdersDelegate = new EndOperationDelegate(this.OnEndGetOrders);
            }
            if ((this.onGetOrdersCompletedDelegate == null)) {
                this.onGetOrdersCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetOrdersCompleted);
            }
            base.InvokeAsync(this.onBeginGetOrdersDelegate, null, this.onEndGetOrdersDelegate, this.onGetOrdersCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult gcafeApp.gcafeSvc.IgcafeSvc.BeginGetMenu(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetMenu(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<gcafeApp.gcafeSvc.MenuItem> gcafeApp.gcafeSvc.IgcafeSvc.EndGetMenu(System.IAsyncResult result) {
            return base.Channel.EndGetMenu(result);
        }
        
        private System.IAsyncResult OnBeginGetMenu(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((gcafeApp.gcafeSvc.IgcafeSvc)(this)).BeginGetMenu(callback, asyncState);
        }
        
        private object[] OnEndGetMenu(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<gcafeApp.gcafeSvc.MenuItem> retVal = ((gcafeApp.gcafeSvc.IgcafeSvc)(this)).EndGetMenu(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetMenuCompleted(object state) {
            if ((this.GetMenuCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetMenuCompleted(this, new GetMenuCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetMenuAsync() {
            this.GetMenuAsync(null);
        }
        
        public void GetMenuAsync(object userState) {
            if ((this.onBeginGetMenuDelegate == null)) {
                this.onBeginGetMenuDelegate = new BeginOperationDelegate(this.OnBeginGetMenu);
            }
            if ((this.onEndGetMenuDelegate == null)) {
                this.onEndGetMenuDelegate = new EndOperationDelegate(this.OnEndGetMenu);
            }
            if ((this.onGetMenuCompletedDelegate == null)) {
                this.onGetMenuCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetMenuCompleted);
            }
            base.InvokeAsync(this.onBeginGetMenuDelegate, null, this.onEndGetMenuDelegate, this.onGetMenuCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult gcafeApp.gcafeSvc.IgcafeSvc.BeginGetMenuCatalogs(string rootCata, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetMenuCatalogs(rootCata, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<gcafeApp.gcafeSvc.MenuCatalog> gcafeApp.gcafeSvc.IgcafeSvc.EndGetMenuCatalogs(System.IAsyncResult result) {
            return base.Channel.EndGetMenuCatalogs(result);
        }
        
        private System.IAsyncResult OnBeginGetMenuCatalogs(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string rootCata = ((string)(inValues[0]));
            return ((gcafeApp.gcafeSvc.IgcafeSvc)(this)).BeginGetMenuCatalogs(rootCata, callback, asyncState);
        }
        
        private object[] OnEndGetMenuCatalogs(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<gcafeApp.gcafeSvc.MenuCatalog> retVal = ((gcafeApp.gcafeSvc.IgcafeSvc)(this)).EndGetMenuCatalogs(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetMenuCatalogsCompleted(object state) {
            if ((this.GetMenuCatalogsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetMenuCatalogsCompleted(this, new GetMenuCatalogsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetMenuCatalogsAsync(string rootCata) {
            this.GetMenuCatalogsAsync(rootCata, null);
        }
        
        public void GetMenuCatalogsAsync(string rootCata, object userState) {
            if ((this.onBeginGetMenuCatalogsDelegate == null)) {
                this.onBeginGetMenuCatalogsDelegate = new BeginOperationDelegate(this.OnBeginGetMenuCatalogs);
            }
            if ((this.onEndGetMenuCatalogsDelegate == null)) {
                this.onEndGetMenuCatalogsDelegate = new EndOperationDelegate(this.OnEndGetMenuCatalogs);
            }
            if ((this.onGetMenuCatalogsCompletedDelegate == null)) {
                this.onGetMenuCatalogsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetMenuCatalogsCompleted);
            }
            base.InvokeAsync(this.onBeginGetMenuCatalogsDelegate, new object[] {
                        rootCata}, this.onEndGetMenuCatalogsDelegate, this.onGetMenuCatalogsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult gcafeApp.gcafeSvc.IgcafeSvc.BeginGetMenuItemByCatalogId(int cataId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetMenuItemByCatalogId(cataId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<gcafeApp.gcafeSvc.MenuItem> gcafeApp.gcafeSvc.IgcafeSvc.EndGetMenuItemByCatalogId(System.IAsyncResult result) {
            return base.Channel.EndGetMenuItemByCatalogId(result);
        }
        
        private System.IAsyncResult OnBeginGetMenuItemByCatalogId(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int cataId = ((int)(inValues[0]));
            return ((gcafeApp.gcafeSvc.IgcafeSvc)(this)).BeginGetMenuItemByCatalogId(cataId, callback, asyncState);
        }
        
        private object[] OnEndGetMenuItemByCatalogId(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<gcafeApp.gcafeSvc.MenuItem> retVal = ((gcafeApp.gcafeSvc.IgcafeSvc)(this)).EndGetMenuItemByCatalogId(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetMenuItemByCatalogIdCompleted(object state) {
            if ((this.GetMenuItemByCatalogIdCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetMenuItemByCatalogIdCompleted(this, new GetMenuItemByCatalogIdCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetMenuItemByCatalogIdAsync(int cataId) {
            this.GetMenuItemByCatalogIdAsync(cataId, null);
        }
        
        public void GetMenuItemByCatalogIdAsync(int cataId, object userState) {
            if ((this.onBeginGetMenuItemByCatalogIdDelegate == null)) {
                this.onBeginGetMenuItemByCatalogIdDelegate = new BeginOperationDelegate(this.OnBeginGetMenuItemByCatalogId);
            }
            if ((this.onEndGetMenuItemByCatalogIdDelegate == null)) {
                this.onEndGetMenuItemByCatalogIdDelegate = new EndOperationDelegate(this.OnEndGetMenuItemByCatalogId);
            }
            if ((this.onGetMenuItemByCatalogIdCompletedDelegate == null)) {
                this.onGetMenuItemByCatalogIdCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetMenuItemByCatalogIdCompleted);
            }
            base.InvokeAsync(this.onBeginGetMenuItemByCatalogIdDelegate, new object[] {
                        cataId}, this.onEndGetMenuItemByCatalogIdDelegate, this.onGetMenuItemByCatalogIdCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override gcafeApp.gcafeSvc.IgcafeSvc CreateChannel() {
            return new IgcafeSvcClientChannel(this);
        }
        
        private class IgcafeSvcClientChannel : ChannelBase<gcafeApp.gcafeSvc.IgcafeSvc>, gcafeApp.gcafeSvc.IgcafeSvc {
            
            public IgcafeSvcClientChannel(System.ServiceModel.ClientBase<gcafeApp.gcafeSvc.IgcafeSvc> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginDoWork(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("DoWork", _args, callback, asyncState);
                return _result;
            }
            
            public void EndDoWork(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("DoWork", _args, result);
            }
            
            public System.IAsyncResult BeginGetOrders(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetOrders", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<gcafeApp.gcafeSvc.Order> EndGetOrders(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<gcafeApp.gcafeSvc.Order> _result = ((System.Collections.ObjectModel.ObservableCollection<gcafeApp.gcafeSvc.Order>)(base.EndInvoke("GetOrders", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetMenu(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetMenu", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<gcafeApp.gcafeSvc.MenuItem> EndGetMenu(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<gcafeApp.gcafeSvc.MenuItem> _result = ((System.Collections.ObjectModel.ObservableCollection<gcafeApp.gcafeSvc.MenuItem>)(base.EndInvoke("GetMenu", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetMenuCatalogs(string rootCata, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = rootCata;
                System.IAsyncResult _result = base.BeginInvoke("GetMenuCatalogs", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<gcafeApp.gcafeSvc.MenuCatalog> EndGetMenuCatalogs(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<gcafeApp.gcafeSvc.MenuCatalog> _result = ((System.Collections.ObjectModel.ObservableCollection<gcafeApp.gcafeSvc.MenuCatalog>)(base.EndInvoke("GetMenuCatalogs", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetMenuItemByCatalogId(int cataId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = cataId;
                System.IAsyncResult _result = base.BeginInvoke("GetMenuItemByCatalogId", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<gcafeApp.gcafeSvc.MenuItem> EndGetMenuItemByCatalogId(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<gcafeApp.gcafeSvc.MenuItem> _result = ((System.Collections.ObjectModel.ObservableCollection<gcafeApp.gcafeSvc.MenuItem>)(base.EndInvoke("GetMenuItemByCatalogId", _args, result)));
                return _result;
            }
        }
    }
}
