//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gcafeWeb40
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu_catalog
    {
        public menu_catalog()
        {
            this.menu = new HashSet<menu>();
            this.menu_catalog1 = new HashSet<menu_catalog>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> parent_id { get; set; }
        public bool locked { get; set; }
    
        public virtual ICollection<menu> menu { get; set; }
        public virtual ICollection<menu_catalog> menu_catalog1 { get; set; }
        public virtual menu_catalog menu_catalog2 { get; set; }
    }
}
