//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gcafePrnConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class method
    {
        public method()
        {
            this.order_detail_method = new HashSet<order_detail_method>();
        }
    
        public int id { get; set; }
        public Nullable<int> method_catalog_id { get; set; }
        public string name { get; set; }
    
        public virtual method_catalog method_catalog { get; set; }
        public virtual ICollection<order_detail_method> order_detail_method { get; set; }
    }
}
